stocks:
  -
    stock: TEA
    type: COMMON
    lastDividend: 0
    parValue: 100
  -
    stock: POP
    type: COMMON
    lastDividend: 8
    parValue: 100
  -
    stock: ALE
    type: COMMON
    lastDividend: 23
    parValue: 60
  -
    stock: GIN
    type: PREFERRED
    lastDividend: 8
    fixedDividend: 0.02
    parValue: 100
  -
    stock: JOE
    type: COMMON
    lastDividend: 13
    parValue: 250

